# Generated by Django 6.0 on 2025-12-26 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inspection_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('receiver_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='type', max_length=50, null=True)),
                ('locations', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assigns',
            fields=[
                ('request', models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.inspectionrequest')),
            ],
            options={
                'db_table': 'assigns',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submits',
            fields=[
                ('transaction', models.ForeignKey(db_column='t_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.transaction')),
            ],
            options={
                'db_table': 'submits',
                'managed': False,
            },
        ),
    ]
