# Generated by Django 5.1.7 on 2025-12-25 22:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionreport',
            name='inspection_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
