# """
# Django settings for ubr project.
# Generated by 'django-admin startproject' using Django 6.0.
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """
# from pathlib import Path
# import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-512rm7tm8sdtrp86194*&+4be@bo+w7%+!*du4nakw(9d(0*)^'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

# # Application definition
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'myapp',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'ubr.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],  # CHANGED: Added templates directory
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',  # ADDED
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'ubr.wsgi.application'

# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ubr',  
#         'USER': 'ubr_user',
#         'PASSWORD': 'ubr_nsm123',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/
# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Dhaka'  # CHANGED: Set to Bangladesh timezone

# USE_I18N = True

# USE_TZ = True

# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/
# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / 'static']  # ADDED: For development static files
# STATIC_ROOT = BASE_DIR / 'staticfiles'    # ADDED: For production static files

# # Media files (User uploaded files)
# MEDIA_URL = '/media/'  # ADDED
# MEDIA_ROOT = BASE_DIR / 'media'  # ADDED

# # Custom User Model
# AUTH_USER_MODEL = 'myapp.CustomUser'  # ADDED: Use custom user model

# # Authentication URLs
# LOGIN_URL = '/login/'  # ADDED
# LOGIN_REDIRECT_URL = '/dashboard/'  # ADDED
# LOGOUT_REDIRECT_URL = '/login/'  # ADDED

# # Session settings
# SESSION_COOKIE_AGE = 1209600  # ADDED: 2 weeks in seconds
# SESSION_SAVE_EVERY_REQUEST = False  # ADDED

# # Message tags for Bootstrap compatibility
# from django.contrib.messages import constants as messages  # ADDED
# MESSAGE_TAGS = {  # ADDED
#     messages.DEBUG: 'debug',
#     messages.INFO: 'info',
#     messages.SUCCESS: 'success',
#     messages.WARNING: 'warning',
#     messages.ERROR: 'danger',
# }

# # Default primary key field type
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'  # ADDED


######### Add this to your existing settings.py

# Custom Authentication Backend
AUTHENTICATION_BACKENDS = [
    'myapp.backends.EmailBackend',  # Custom email backend
    'django.contrib.auth.backends.ModelBackend',  # Default backend
]

# Custom User Model
AUTH_USER_MODEL = 'myapp.CustomUser'

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = False

<<<<<<< HEAD
# Message tags for Bootstrap compatibility
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}
=======
WSGI_APPLICATION = 'ubr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ubr',  
#         'USER': 'ubr_user',
#         'PASSWORD': 'ubr_nsm123',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'property_inspection_db',
        'USER': 'root',
        'PASSWORD': '12345@@',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Serve project-level static files during development
# The repository has a top-level `static/` folder at the repo root (one level above BASE_DIR).
# Use BASE_DIR.parent to point to that directory so runserver can find `/static/css/style.css`.
STATICFILES_DIRS = [BASE_DIR.parent / "static"]


LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
# Default primary key type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# End of settings.py
>>>>>>> sadi
